language: node_js
node_js:
- iojs
env:
  global:
  - secure: WXkeUKwWKTv2uUCyIiDdQ0e5gQCoX9gGj6wiNh9G7IATqcecxTw6cpQGj3J8YWDIjbtNXfAkJwohhGtXYr7VnkXRA1s0POYM+8cvM5I+ZDtZkXM9EvCwMYxf9XZ8qQ/4fegeSoZqfx1qgh+Sfh6Wp93I4W+AfB8VONLIGgXr172QGwYmkynPpC//mYA6sUZoQo4Y796PtBblc+7oM0a5A5chQ5r1CVqPqRZ/i9aNrH2UTdYjCMNE395LqwHSJGk5eunT5ebA4OcClme1wL78MJtGS1ZZIOEHSBv7mBrOcp29kYknc/m1PaOYBMdppmRBLr6Q5oUg8QzaILW2TypsWkosWpSlbemW1lsutqlFRkmtsjfX3ZVOoeIx/7J9v+pDA2gb7VMtNzwlkRpcLfHBmfuXuiPNXwLS1Ogl2D8JUD+rjwB3FI6pE2zZqNL7zMe7yhCQ/1wqGdlNqB1Ifb9T2RRkDCEUr+dw3sGn6Ecgk4XThUwY3vVzABj0C906Wc7UpsVvf1qjLCRg48lYG8kmhLqEylL+IUs3XXMSv69/YLxnDvRdF/d1FZHWKcoTeWYmXr3k1q0ePYEDXpX6/8MXWix1Qql4AAOjIxOgRufBPlDWe6QS2b97K4OPo+m3cf/RaLPz+jUOpf59l6CNnceBYLKs00Taf0KSgs+YVADAV6M=
before_script:
- git config --global user.email "basaratali@gmail.com"
- git config --global user.name "Travis-CI"
- git remote set-url origin https://github.com/TypeStrong/ntypescript.git
script:
- bash prepare.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global push.default matching
- bash release.sh
branches:
  only:
  - master
deploy:
  provider: npm
  email: basaratali@gmail.com
  api_key:
    secure: s/KSMaTnT6JdVOmaw5n3KnA5piUjxopXjOEH/k2uTph2zY7XVvGw83UX797IUDNTRKAX1OrgfaB+VQ+bT1Tf7KAqOgy1MtvS/lFJMMmRO5U1HI8Dj5NXWQ87GFHO1/iDZgVxRju/kkjxG/WkBfkJCex0B2smqC0HFWZKBOWlBLgjJGHs+gZV02CzWQc72kZ9PRTxbeh5Lid2D7NXAY1BfFKHyvAlibd+3sZTdjfeVQzyGg94I6pNQOpr1O0MzKv7ttZ+7iEN2cLoH9t/2927LdR1lIlyl7ArE/UY5ob4W9PpwXYXjb4O1j7vvo/S33bgXzKy1cwL1udoe5B9MvUoU8Qg64ffqyD+RRhj2ZgnnXhYIovDwOEYFbRSMgaYgoI54ThpyQXZbvwxuqWxMh5rSeUGzi5Ah36Z6zqfSYo5J7XC+mXUiqBfIXNjOpbw43rASLiM25/rMvXVDlEeDh1rgpIKDu2DVuX0Zyw4apNu+7cjlFfZ0iQwVAN5xzzJ2DOgPNosjbWe5g4RR5t2bBq9CxDYxQPNB7x1GhUk82qlij23ssoLfvNyYuLaoILuCyDly1FLHr1U6Q9VBOKvLR7qqjn0F7ZpEi8RKbNgpqNWf7ExXDOcNuoHHuHJWvKMDfj8xlkV9PeWFkCiYtm6xr1DQd/6HUkN+uh/d8SjNkgJlPM=
  on:
    repo: TypeStrong/ntypescript
